#!/usr/bin/env bash

# this is just an example!
# add your autostart stuffs here
xbacklight -set 5 &
#xmodmap ~/.xmodmap-sid &
picom &
xrdb merge ~/.config/chadwm/.Xresources &
feh --bg-fill ~/Pictures/pink_cat.png &

# run bar script and dwm ( do not remove this )
~/.config/chadwm/scripts/bar.sh &
dwm
